'use server';

import nodemailer from 'nodemailer';

export async function sendEmail(formData: FormData) {
  const name = formData.get('name') as string;
  const email = formData.get('email') as string;
  const phone = formData.get('phone') as string;
  const businessName = formData.get('businessName') as string;
  const businessType = formData.get('businessType') as string;
  const estimatedVolume = formData.get('estimatedVolume') as string;
  const message = formData.get('message') as string;

  // Create transporter
  const transporter = nodemailer.createTransport({
    host: 'smtp.gmail.com',
    port: 465,
    secure: true, // Use SSL/TLS
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_PASS, // App password
    },
  });

  try {
    // Send email to the owner
    await transporter.sendMail({
      from: `"Bharat H2O Lead Form" <${process.env.GMAIL_USER}>`,
      to: process.env.GMAIL_USER, // The receiver
      subject: `New Lead: ${name} (${businessName})`,
      text: `
        Name: ${name}
        Email: ${email}
        Phone: ${phone}
        Business Name: ${businessName}
        ${businessType ? `Business Type: ${businessType}` : ''}
        ${estimatedVolume ? `Estimated Monthly Volume: ${estimatedVolume}` : ''}
        Message: ${message}
      `,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px;">
          <h2 style="color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px;">New Lead Recorded</h2>
          <p><strong>Customer Name:</strong> ${name}</p>
          <p><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
          <p><strong>Phone:</strong> <a href="tel:${phone}">${phone}</a></p>
          <p><strong>Business:</strong> ${businessName}</p>
          ${businessType ? `<p><strong>Business Type:</strong> ${businessType}</p>` : ''}
          ${estimatedVolume ? `<p><strong>Estimated Volume:</strong> ${estimatedVolume}</p>` : ''}
          <div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; margin-top: 20px;">
            <p style="margin: 0; font-weight: bold; color: #475569;">Message/Requirements:</p>
            <p style="margin-top: 10px; line-height: 1.5; color: #1e293b;">${message || "No additional message provided."}</p>
          </div>
          <p style="margin-top: 30px; font-size: 12px; color: #94a3b8; text-align: center;">
            This email was generated by the Bharat H2O Contact Form.
          </p>
        </div>
      `,
    });

    // Send "Thank You" email to the customer
    await transporter.sendMail({
      from: `"Bharat H2O Support" <${process.env.GMAIL_USER}>`,
      to: email, // The customer
      subject: `Thank you for choosing Bharat H2O, ${name}!`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
          <div style="text-align: center; padding-bottom: 20px;">
            <h1 style="color: #2563eb; margin: 0;">Bharat H2O</h1>
            <p style="color: #64748b; font-size: 14px;">Premium Packaged Drinking Water</p>
          </div>
          <div style="padding: 20px; background-color: #f0f7ff; border-radius: 8px;">
            <p style="font-size: 16px; color: #1e293b;">Dear <strong>${name}</strong>,</p>
            <p style="line-height: 1.6; color: #334155;">
              Thank you for reaching out to Bharat H2O! We've received your request for <strong>${businessName}</strong> and we're excited to help you elevate your brand.
            </p>
            <p style="line-height: 1.6; color: #334155;">
              Our team is currently reviewing your requirements and one of our dedicated brand experts will get back to you with a custom quote and design mockup within <strong>24 hours</strong>.
            </p>
          </div>
          <div style="margin-top: 30px; text-align: center;">
            <p style="margin-bottom: 5px; color: #475569;">Need immediate assistance?</p>
            <p style="font-weight: bold; color: #2563eb;">Call us: +91 7898595612</p>
          </div>
          <p style="margin-top: 40px; font-size: 12px; color: #94a3b8; text-align: center; border-top: 1px solid #f1f5f9; padding-top: 20px;">
            Bharat H2O - India's Most Trusted Hospitality Partner for Custom Branded Water.
          </p>
        </div>
      `,
    });

    return { success: true };
  } catch (error) {
    console.error('Nodemailer Error:', error);
    return { success: false, error: 'Failed to send email.' };
  }
}
